# Generated by Django 3.0.3 on 2021-01-24 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personagens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casas',
            fields=[
                ('id_casa', models.AutoField(primary_key=True, serialize=False)),
                ('nome_casa', models.CharField(max_length=30)),
                ('lema', models.CharField(blank=True, max_length=60, null=True)),
                ('simbolo', models.ImageField(blank=True, null=True, upload_to='imagens')),
            ],
            options={
                'db_table': 'casas"."Casas',
                'ordering': ['nome_casa'],
            },
        ),
        migrations.CreateModel(
            name='Membros',
            fields=[
                ('id_membro', models.AutoField(primary_key=True, serialize=False)),
                ('papel_casa', models.CharField(blank=True, choices=[('Rei', 'Rei'), ('Rainha', 'Rainha'), ('Príncipe herdeiro', 'Príncipe herdeiro'), ('Príncipe', 'Príncipe'), ('Princesa', 'Princesa')], max_length=50, null=True)),
                ('id_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casas.Casas')),
                ('id_personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membro', to='personagens.Personagens')),
            ],
            options={
                'db_table': 'casas"."Membros',
                'ordering': ['id_membro'],
            },
        ),
        migrations.CreateModel(
            name='Caracteristicas',
            fields=[
                ('id_caracteristica', models.AutoField(primary_key=True, serialize=False)),
                ('caracteristica', models.CharField(max_length=250)),
                ('id_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casas.Casas')),
            ],
            options={
                'db_table': 'casas"."Caracteristicas',
                'ordering': ['id_caracteristica'],
            },
        ),
    ]
