# Generated by Django 3.0.3 on 2021-01-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membros',
            name='papel_casa',
            field=models.CharField(blank=True, choices=[('Rei', 'Rei'), ('Rainha', 'Rainha'), ('Príncipe herdeiro', 'Príncipe herdeiro'), ('Príncipe', 'Príncipe'), ('Princesa', 'Princesa'), ('Sem papel definido', 'Sem papel definido')], max_length=50, null=True),
        ),
    ]
