# Generated by Django 3.0.3 on 2021-02-02 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0002_auto_20210126_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membros',
            options={'ordering': ['id_personagem__nome']},
        ),
    ]
