# Generated by Django 3.0.3 on 2021-01-24 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id_autor', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=70)),
                ('ano_nascimento', models.IntegerField()),
                ('pais_nascimento', models.CharField(choices=[('BR', 'Brasil'), ('USA', 'Estados Unidos')], max_length=3)),
                ('pagina', models.URLField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'livros"."Autores',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Capitulos',
            fields=[
                ('id_capitulo', models.AutoField(primary_key=True, serialize=False)),
                ('num_capitulo', models.IntegerField()),
                ('nome_capitulo', models.CharField(blank=True, max_length=30, null=True)),
                ('pagina_inicio', models.IntegerField()),
                ('pagina_termino', models.IntegerField()),
            ],
            options={
                'db_table': 'livros"."Capitulos',
                'ordering': ['num_capitulo'],
            },
        ),
        migrations.CreateModel(
            name='Editoras',
            fields=[
                ('id_editora', models.AutoField(primary_key=True, serialize=False)),
                ('editora', models.CharField(max_length=30)),
                ('razao_social', models.CharField(blank=True, max_length=50, null=True)),
                ('pagina', models.URLField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'livros"."Editoras',
                'ordering': ['editora'],
            },
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id_livro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=80)),
                ('isbn', models.CharField(max_length=20)),
                ('edicao_numero', models.IntegerField()),
                ('edicao_ano', models.IntegerField()),
                ('num_paginas', models.IntegerField()),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.Autores')),
                ('id_editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.Editoras')),
            ],
            options={
                'db_table': 'livros"."Livros',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('valor_inicial', models.CharField(max_length=50)),
                ('valor_final', models.CharField(max_length=50)),
                ('id_capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.Capitulos')),
            ],
            options={
                'db_table': 'livros"."Eventos',
                'ordering': ['id_evento'],
            },
        ),
        migrations.AddField(
            model_name='capitulos',
            name='id_livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.Livros'),
        ),
    ]
