# Generated by Django 3.0.3 on 2021-01-24 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personagens',
            fields=[
                ('id_personagem', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(blank=True, max_length=30, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('apelido', models.CharField(blank=True, max_length=30, null=True)),
                ('especie', models.CharField(choices=[('Humano', 'Humano'), ('Lobo', 'Lobo')], max_length=30)),
            ],
            options={
                'db_table': 'personagens"."Personagens',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TpCaracteristica',
            fields=[
                ('id_tp_caracteristica', models.AutoField(primary_key=True, serialize=False)),
                ('tp_caracteristica', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'personagens"."TpCaracteristica',
                'ordering': ['tp_caracteristica'],
            },
        ),
        migrations.CreateModel(
            name='Caracterizacao',
            fields=[
                ('id_caracterizacao', models.AutoField(primary_key=True, serialize=False)),
                ('caracteristica', models.CharField(max_length=50)),
                ('id_personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personagens.Personagens')),
                ('id_tp_caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personagens.TpCaracteristica')),
            ],
            options={
                'db_table': 'personagens"."Caracterizacao',
                'ordering': ('id_tp_caracteristica', 'caracteristica'),
            },
        ),
    ]
